@id=00000000-0000-0000-0000-000000000000

PUT http://localhost:5083/recipes/{{id}}
Content-Type: application/json

{
    "name": "Meat Lovers",
    "description": "Meat everything! Meat on everything recipe..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "lastModifiedDateTime": "2022-04-06T12:00:00",
    "savory": [
        "Sausage",
        "Chilis",
        "Eggs",
        "Chicken"
    ],
    "Sweet": [
        "Bacon jam"
    ]
}